# Generated by Django 3.2 on 2024-04-02 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFPapp', '0025_alter_post_a3_c2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_infos',
            name='anciennete_mois',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
